services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    image: bapeda-profile
    container_name: bapeda-profile
    restart: always
    ports:
      - "127.0.0.1:3031:3031"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    cpus: "0.5"
    mem_limit: "512m"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

networks:
  app-network:
