services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-build-time-placeholder-not-for-production}
        NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT: "https://ik.imagekit.io/bapendajambi"
        NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY: "public_BZ7r8XP67ODQGGmLmAGXdrf8Kjw="
    image: bapenda-profile
    container_name: bapenda-profile
    restart: always
    ports:
      - "0.0.0.0:3031:3031"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    cpus: "0.5"
    mem_limit: "512m"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

networks:
  app-network:
